configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/acme-corp-vnikhilbuddhavarapu%2Facme-blog-1f61b8225e7f8edc5f7ea0cdaef3f63d41f20ca7ee0a6d8747c0dee5a65651a2.yml
openapi_spec_hash: ae69a9c07bb1d1c2750fb0c22c7aa5e3
config_hash: 962b5e5b45af9ae08f71ea22fce4e3ae
